### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rchgonzaga** [rchgonzaga/orgnlls#1]
First part of the project.

- [ ] Create project standards
- [ ] Create form standards
- [ ] Define Login method and security methods
- [ ] Validation standards
- [ ] Layout definition
